#!/usr/bin/env python3
"""Extract schema snapshot from app.py users DDL for Spec Kit ontology."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
APP = ROOT / "app.py"
OUT = ROOT / ".specify" / "ontology" / "snapshots" / "schema.snapshot.json"

# Column name → (xsd local name, owl property local name)
COLUMN_MAP = {
    "id": ("integer", "userId"),
    "email": ("string", "email"),
    "name": ("string", "name"),
    "password_hash": ("string", "passwordHash"),
    "role": ("string", "roleCode"),
    "created_at": ("string", "createdAt"),
    "updated_at": ("string", "updatedAt"),
}


def extract_users_columns(source: str) -> list[dict]:
    match = re.search(
        r"CREATE TABLE IF NOT EXISTS users\s*\((.*?)\)",
        source,
        re.DOTALL | re.IGNORECASE,
    )
    if not match:
        raise SystemExit("Could not find CREATE TABLE users in app.py")

    body = match.group(1)
    columns: list[dict] = []
    for raw in body.split(","):
        line = " ".join(raw.strip().split())
        if not line or line.upper().startswith("PRIMARY KEY"):
            continue
        parts = line.split()
        name = parts[0].strip("`\"")
        if name.upper() in {"PRIMARY", "UNIQUE", "CONSTRAINT", "FOREIGN"}:
            continue
        sql_type = parts[1].upper() if len(parts) > 1 else "TEXT"
        meta = COLUMN_MAP.get(name)
        if not meta:
            raise SystemExit(f"Unmapped column in users DDL: {name}")
        xsd, prop = meta
        columns.append(
            {
                "name": name,
                "sqlType": sql_type,
                "xsd": xsd,
                "property": prop,
                "notNull": "NOT NULL" in line.upper(),
                "unique": "UNIQUE" in line.upper(),
            }
        )
    return columns


def main() -> int:
    source = APP.read_text(encoding="utf-8")
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    columns = extract_users_columns(source)
    payload = {
        "$schemaComment": "AUTO-GENERATED by .specify/scripts/extract_schema_snapshot.py — DO NOT HAND-EDIT.",
        "source": "app.py",
        "sourceSha256": digest,
        "tables": {
            "users": {
                "class": "User",
                "columns": columns,
            }
        },
        "roles": ["driver", "pm", "admin"],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(columns)} columns, sha256={digest[:12]}…)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
