#!/usr/bin/env python3
"""Regenerate auth_domain.generated.ttl and auth_domain.shacl.enums.ttl from snapshot."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from ontology_map import EXTRA_CLASSES, ROLE_CODES

ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
SNAPSHOT = ONTOLOGY / "snapshots" / "schema.snapshot.json"
GENERATED = ONTOLOGY / "auth_domain.generated.ttl"
ENUMS = ONTOLOGY / "auth_domain.shacl.enums.ttl"

NS = "https://aes-lighting.com/ns/auth#"
GEN_ONT = "https://aes-lighting.com/ns/auth/generated"
ENUM_ONT = "https://aes-lighting.com/ns/auth/shacl/enums"


def load_snapshot() -> dict:
    if not SNAPSHOT.exists():
        raise SystemExit("Missing schema snapshot; run extract_schema_snapshot.py first")
    return json.loads(SNAPSHOT.read_text(encoding="utf-8"))


def emit_generated(snap: dict) -> str:
    lines = [
        "# AUTO-GENERATED by .specify/scripts/generate_ontology.py — DO NOT HAND-EDIT.",
        f"@prefix auth: <{NS}> .",
        "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
        "@prefix dct:  <http://purl.org/dc/terms/> .",
        "",
        f"<{GEN_ONT}>",
        "    a owl:Ontology ;",
        '    dct:title "Auth Domain Generated TBox" ;',
        f'    owl:versionInfo "0.1.0-baseline" ;',
        f'    rdfs:comment "sourceSha256={snap["sourceSha256"]}" .',
        "",
    ]

    users = snap["tables"]["users"]
    class_name = users["class"]
    lines += [
        f"auth:{class_name}",
        "    a owl:Class ;",
        f'    rdfs:label "{class_name}" ;',
        '    rdfs:comment "Mapped from SQLite table users." .',
        "",
    ]
    for col in users["columns"]:
        prop = col["property"]
        xsd = col["xsd"]
        lines += [
            f"auth:{prop}",
            "    a owl:DatatypeProperty ;",
            f"    rdfs:domain auth:{class_name} ;",
            f"    rdfs:range xsd:{xsd} ;",
            f'    rdfs:label "{prop}" ;',
            f'    rdfs:comment "Column {col["name"]} ({col["sqlType"]})." .',
            "",
        ]

    for extra in EXTRA_CLASSES:
        lines += [
            f"auth:{extra}",
            "    a owl:Class ;",
            f'    rdfs:label "{extra}" ;',
            '    rdfs:comment "Non-table conceptual class (session cookie side)." .',
            "",
        ]

    return "\n".join(lines).rstrip() + "\n"


def emit_enums(snap: dict) -> str:
    roles = snap.get("roles") or list(ROLE_CODES)
    role_list = " ".join(f'"{r}"' for r in roles)
    return f"""# AUTO-GENERATED by .specify/scripts/generate_ontology.py — DO NOT HAND-EDIT.
@prefix auth: <{NS}> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix dct:  <http://purl.org/dc/terms/> .

<{ENUM_ONT}>
    a owl:Ontology ;
    dct:title "Auth Domain SHACL Role Enums" ;
    owl:versionInfo "0.1.0-baseline" ;
    rdfs:comment "sourceSha256={snap["sourceSha256"]}" .

auth:UserRoleCodePropertyShape
    a sh:PropertyShape ;
    sh:path auth:roleCode ;
    sh:datatype xsd:string ;
    sh:minCount 1 ;
    sh:maxCount 1 ;
    sh:in ( {role_list} ) .
"""


def main() -> int:
    snap = load_snapshot()
    GENERATED.write_text(emit_generated(snap), encoding="utf-8")
    ENUMS.write_text(emit_enums(snap), encoding="utf-8")
    print(f"Wrote {GENERATED.relative_to(ROOT)}")
    print(f"Wrote {ENUMS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
